name: Android

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    name: NDK-R28C
    runs-on: ubuntu-latest

    steps:
    - name: Setup Android NDK R28C
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r28c
        add-to-path: false
    - uses: actions/checkout@v3
    - name: build
      run: |
        cd ./scripts/build-android/
        echo ${{ steps.setup-ndk.outputs.ndk-path }}
        source ./build-android -n ${{ steps.setup-ndk.outputs.ndk-path }}
