name: Android

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r28c
        add-to-path: false

    # 执行你的编译脚本
    - name: Build
      run: |
        cd ./scripts/build-android/
        chmod +x ./build-android
        source ./build-android -n ${{ steps.setup-ndk.outputs.ndk-path }}

    # ==========================================
    # ✅ 下面这一步：GitHub 自动打包 + 自动生成下载
    # ==========================================
    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: android-openssl-srt-build  # 压缩包名字
        path: output/                   # 你编译后输出的根目录（里面包含 libs + include）
